config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "home/index"

  # Dream Journal App
  resources :dreams, only: [:new, :create, :index, :show, :destroy]
  get "/dreams/search", to: "dreams#search", as: "search_dreams"
  get "/dream_journal", to: "dreams#index", as: "dream_journal"
  
  # Work Journal App
  resources :work_days, only: [:new, :create, :index, :show, :destroy] do
    resources :work_entries, only: [:new, :create, :destroy]
    collection do
      get :search
    end
  end
  get "/work_journal", to: "work_days#index", as: "work_journal"

  # Order Fulfillment App
  resources :orders, only: [:index, :show, :update] do
    collection do
      post :import
      get :shipped
      get :delivered
    end
    member do
      patch :mark_delivered
    end
  end
  get "/order_fulfillment", to: "orders#index", as: "order_fulfillment"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def dream_journal
  end

  def work_journal
  end

  def order_fulfillment
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/dream_journal.html.erb
<h1>Dream Journal (Coming Soon)</h1>
<p>This app will help you log and analyze dreams with AI support.</p>

app/views/home/index.html.erb
<div class="landing-container">
  <h1>Welcome to Rails App</h1>
  <p>Select an app to get started:</p>

  <div class="button-group">
    <%= link_to "Dream Journal (AI)", dream_journal_path, class: "app-button" %>
    <%= link_to "Work Journal (AI)", work_journal_path, class: "app-button" %>
    <%= link_to "Order Fulfillment (Shopify)", order_fulfillment_path, class: "app-button" %>
  </div>
</div> 

app/views/home/order_fulfillment.html.erb
<h1>Order Fulfillment (Coming Soon)</h1>
<p>This app will process Shopify Orders.</p>

app/views/home/work_journal.html.erb
<h1>Work Journal (Coming Soon)</h1>
<p>This app will help you log and analyze work with AI support.</p>